import { Report } from './report-data-layout';

export const REPORTS: Report[] = [
    {
        id: "One",
        select: false,
        print: "noprint",
        title: "LANDLORD REPRESENTATION – LEASING, DEVELOPMENT & MANAGEMENT",
        location:"3650 Milwaukee St, Madison, WI",
        picture: "assets/Images/3650 Milwaukee St.jpg",
        secondColumnName: "Project Date",
        secondColumnInput: "June 2018 through Present",
        projectScope: "Key Commercial Real Estate was engaged by Leo Ritter & Co to conduct an analysis of the future options for the property after losing a long term tenant, Swiss Colony. Analysis included lease and sale valuations and recommendation of highest & best use given the site’s condition, attributes, zoning, neighborhood special area plan and market conditions. The strategic plan resulted in launching efforts to secure a new tenant for reuse of the existing aging warehouse building and keep the existing zoning. During the marketing efforts, the ideal tenant was identified and significant efforts were required to accommodate their specific needs by assembling a team of professionals including architects, engineers, GC, and legal counsel to manage the transition into a redevelopment project. Key Commercial acted as leasing agent and project manager handling assemblage of two additional land parcels, project proformas, secured financing bids, assisted with city entitlements/approval, negotiated a complex lease with Amazon and acted as Landlord’s trusted local advisor throughout the project. The end result of a long term lease with a high credit tenant was ideal for this Landlord. A great relationship has been formed between Landlord and Key Commercial resulting in ongoing property management services and a future multi-family housing project on surplus land remaining from this transaction.",
    },
    {
        id: "Two",
        select: false,
        print: "noprint",
        title: "TENANT REPRESENTATION – 101,000 SF INDUSTRIAL LEASE",
        location: "1763 N Bristol Street, Sun Prairie, WI",
        picture: "assets/Images/1763 N Bristol St.jpg",
        secondColumnName: "PROJECT DESCRIPTION:",
        secondColumnInput: "Present Aprilaire in lease negotiation for 101,000 square feet of warehouse and office",
        projectScope: "Key Commercial began working with Aprilaire in mid-2019 when they were looking for approximately 10,000 SF of expansion space for their current headquarters on E. Washington and E. Main Street in Madison. A lease was negotiated for the additional space but ultimately put on pause with the onset of the pandemic in 2020. Over the course of 2020 and into 2021, Aprilaire continued to expand at an exceedingly rapid rate, in part due to an increased demand for their air quality/air purification systems. In turn, the expansion space needed by the company continued to increase until it was a 100,000+ SF requirement consisting of both office and manufacturing space. The 1763 N Bristol Street property was an ideal solution as it offered a location meeting their general space programming with minimal buildout and was able to be quickly occupied to help meet the growing demand for their products. The building was originally developed for and leased back to Riddell Sports. Riddell discontinued the line of business that was utilizing the property which led to the building being available for sublease. This created an additional layer of complication for the lease negotiation and approval as it involved both the master lessor and Riddell as the sublessor.",
    },
    {
        id: "Three",
        select: false,
        print: "noprint",
        title: "LANDLORD REPRESENTATION – LEASING, DEVELOPMENT & MANAGEMENT",
        location:"3650 Milwaukee St, Madison, WI",
        picture: "assets/Images/3650 Milwaukee St.jpg",
        secondColumnName: "Project Date",
        secondColumnInput: "June 2018 through Present",
        projectScope: "Key Commercial Real Estate was engaged by Leo Ritter & Co to conduct an analysis of the future options for the property after losing a long term tenant, Swiss Colony. Analysis included lease and sale valuations and recommendation of highest & best use given the site’s condition, attributes, zoning, neighborhood special area plan and market conditions. The strategic plan resulted in launching efforts to secure a new tenant for reuse of the existing aging warehouse building and keep the existing zoning. During the marketing efforts, the ideal tenant was identified and significant efforts were required to accommodate their specific needs by assembling a team of professionals including architects, engineers, GC, and legal counsel to manage the transition into a redevelopment project. Key Commercial acted as leasing agent and project manager handling assemblage of two additional land parcels, project proformas, secured financing bids, assisted with city entitlements/approval, negotiated a complex lease with Amazon and acted as Landlord’s trusted local advisor throughout the project. The end result of a long term lease with a high credit tenant was ideal for this Landlord. A great relationship has been formed between Landlord and Key Commercial resulting in ongoing property management services and a future multi-family housing project on surplus land remaining from this transaction.",
    },
    {
        id: "Four",
        select: false,
        print: "noprint",
        title: "TENANT REPRESENTATION – 101,000 SF INDUSTRIAL LEASE",
        location: "1763 N Bristol Street, Sun Prairie, WI",
        picture: "assets/Images/1763 N Bristol St.jpg",
        secondColumnName: "PROJECT DESCRIPTION:",
        secondColumnInput: "Present Aprilaire in lease negotiation for 101,000 square feet of warehouse and office",
        projectScope: "Key Commercial began working with Aprilaire in mid-2019 when they were looking for approximately 10,000 SF of expansion space for their current headquarters on E. Washington and E. Main Street in Madison. A lease was negotiated for the additional space but ultimately put on pause with the onset of the pandemic in 2020. Over the course of 2020 and into 2021, Aprilaire continued to expand at an exceedingly rapid rate, in part due to an increased demand for their air quality/air purification systems. In turn, the expansion space needed by the company continued to increase until it was a 100,000+ SF requirement consisting of both office and manufacturing space. The 1763 N Bristol Street property was an ideal solution as it offered a location meeting their general space programming with minimal buildout and was able to be quickly occupied to help meet the growing demand for their products. The building was originally developed for and leased back to Riddell Sports. Riddell discontinued the line of business that was utilizing the property which led to the building being available for sublease. This created an additional layer of complication for the lease negotiation and approval as it involved both the master lessor and Riddell as the sublessor.",
    },
];